baseURL = "http://liftaris.com/"
languageCode = "en-us"
title = "Kaio"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "game dev, graphics, art"
    githubUsername = "kaiobarb"
    accent = "#D0D059"
    showBorder = true
    backgroundColor = "#140D45"
    font = "Poppins" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "profile.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:kaiobarb@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/kaiobarb/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/Liftaris1/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/kaiobarb/"
    name = "fab fa-linkedin"
    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "fab fa-stack-overflow"
#    weight = 5
